name: Image Resizer PR Pipeline.

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/readme.md'
      - '**/assets/*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn clean test